#!/usr/bin/env python3
from __future__ import annotations

import argparse
import grp
import hashlib
import json
import os
import pwd
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from typing import Any


ROOT = Path(os.environ.get("COLUTTI_DESKTOP_ROOT", Path(__file__).resolve().parents[1]))
STATE = Path(
    os.environ.get(
        "COLUTTI_DESKTOP_STATE",
        Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state"))
        / "colutti-desktop",
    )
)


def atomic_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(value, stream, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def atomic_text(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write(value)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def default_settings() -> dict[str, Any]:
    return json.loads((ROOT / "settings/default.json").read_text())


def build_hdr_calibration_target(
    current: dict[str, Any],
    *,
    sdrbrightness: float,
    sdrsaturation: float,
    sdr_eotf: str,
    sdr_min_luminance: float,
    sdr_max_luminance: float,
) -> dict[str, Any]:
    """Build a safe live HDR preview without changing the display layout."""
    target = dict(current)
    target.update({"bitdepth": 10, "color_mode": "hdredid", "vrr": False})
    target["hdr_tuning"] = {
        "supports_wide_color": True,
        "supports_hdr": True,
        "sdrbrightness": sdrbrightness,
        "sdrsaturation": sdrsaturation,
        "sdr_eotf": sdr_eotf,
        "sdr_min_luminance": sdr_min_luminance,
        "sdr_max_luminance": int(round(sdr_max_luminance)),
        "min_luminance": 0.25,
        "max_luminance": 480,
        "max_avg_luminance": 302,
    }
    return target


def render_hdr_calibration_lua(output: str, monitor: dict[str, Any]) -> str:
    expression = MonitorManager._expression(output, monitor)
    return (
        "-- Generated by HDR Calibration. Do not edit manually.\n"
        + expression
        + "\n"
    )


def settings_path() -> Path:
    config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return config / "colutti-desktop/settings.json"


def validate_settings(settings: dict[str, Any]) -> None:
    allowed = {"schema_version", "theme", "theme_override", "monitors", "profile"}
    if not isinstance(settings, dict):
        raise ValueError("settings must be an object")
    missing = allowed - set(settings)
    if missing:
        raise ValueError(f"missing setting: {sorted(missing)[0]}")
    unknown = set(settings) - allowed
    if unknown:
        raise ValueError(f"unknown setting: {sorted(unknown)[0]}")
    if settings.get("schema_version") != 1:
        raise ValueError("unsupported settings schema")
    theme_slugs = {
        path.parent.name for path in (ROOT / "themes").glob("*/manifest.json")
    }
    if settings["theme"] not in theme_slugs:
        raise ValueError(f"invalid theme: {settings['theme']}")
    if not isinstance(settings["theme_override"], bool):
        raise ValueError("theme_override must be boolean")
    if not isinstance(settings["monitors"], dict) or not settings["monitors"]:
        raise ValueError("monitors must be a non-empty object")
    for output, monitor in settings["monitors"].items():
        fields = {
            "mode",
            "position",
            "scale",
            "bitdepth",
            "color_mode",
            "hdr_fullscreen_passthrough",
        }
        if not isinstance(monitor, dict):
            raise ValueError(f"monitor {output} must be an object")
        missing_monitor = fields - set(monitor)
        if missing_monitor:
            raise ValueError(
                f"missing monitor setting for {output}: {sorted(missing_monitor)[0]}"
            )
        optional_fields = {"hdr_tuning"}
        unknown_monitor = set(monitor) - fields - optional_fields
        if unknown_monitor:
            raise ValueError(
                f"unknown monitor setting for {output}: {sorted(unknown_monitor)[0]}"
            )
        if not re.fullmatch(r"\d+x\d+@\d+(?:\.\d+)?", str(monitor["mode"])):
            raise ValueError(f"invalid mode for {output}")
        if not re.fullmatch(r"-?\d+x-?\d+", str(monitor["position"])):
            raise ValueError(f"invalid position for {output}")
        if not 0.5 <= float(monitor["scale"]) <= 4:
            raise ValueError(f"invalid scale for {output}")
        if monitor["bitdepth"] not in {8, 10}:
            raise ValueError(f"invalid bitdepth for {output}")
        if monitor["color_mode"] not in {
            "srgb",
            "wide",
            "hdr",
            "hdredid",
            "dciedid",
            "dp3",
        }:
            raise ValueError(f"invalid color mode for {output}")
        if not isinstance(monitor["hdr_fullscreen_passthrough"], bool):
            raise ValueError(f"HDR flag must be boolean for {output}")
        tuning = monitor.get("hdr_tuning")
        if tuning is not None:
            allowed_tuning = {
                "sdrbrightness", "sdrsaturation", "sdr_eotf",
                "sdr_min_luminance", "sdr_max_luminance", "min_luminance",
                "max_luminance", "max_avg_luminance", "supports_wide_color",
                "supports_hdr",
            }
            if not isinstance(tuning, dict) or set(tuning) - allowed_tuning:
                raise ValueError(f"invalid HDR tuning for {output}")
            for key, value in tuning.items():
                if key == "sdr_eotf":
                    if value not in {"default", "srgb", "gamma22"}:
                        raise ValueError(f"invalid HDR EOTF for {output}")
                elif key in {"supports_wide_color", "supports_hdr"}:
                    if not isinstance(value, bool):
                        raise ValueError(f"invalid HDR capability for {output}: {key}")
                elif not isinstance(value, (int, float)) or isinstance(value, bool):
                    raise ValueError(f"invalid HDR tuning value for {output}: {key}")
    if not isinstance(settings["profile"], dict):
        raise ValueError("profile must be an object")
    profile_fields = {"game", "power", "dnd"}
    if set(settings["profile"]) != profile_fields:
        raise ValueError("profile must contain game, power and dnd")
    if settings["profile"]["game"] not in {"on", "off"}:
        raise ValueError("invalid game profile")
    if settings["profile"]["power"] not in {
        "balanced",
        "performance",
        "power-saver",
    }:
        raise ValueError("invalid power profile")
    if not isinstance(settings["profile"]["dnd"], bool):
        raise ValueError("DND must be boolean")


def read_settings() -> dict[str, Any]:
    path = settings_path()
    settings = json.loads(path.read_text()) if path.exists() else default_settings()
    validate_settings(settings)
    return settings


def replace_settings(source: Path) -> dict[str, Any]:
    settings = json.loads(source.read_text())
    validate_settings(settings)
    destination = settings_path()
    if destination.exists():
        current = json.loads(destination.read_text())
        previous = STATE / "previous-settings.json"
        if current != settings and not previous.exists():
            atomic_json(previous, current)
    atomic_json(destination, settings)
    return settings


def set_monitor_hdr(output: str, enabled: bool) -> dict[str, Any]:
    settings = read_settings()
    monitor = settings["monitors"].get(output)
    if monitor is None:
        raise ValueError(f"unknown monitor: {output}")
    if not monitor["hdr_fullscreen_passthrough"]:
        raise ValueError(f"monitor is not HDR-capable: {output}")
    monitor["bitdepth"] = 10 if enabled else 8
    monitor["color_mode"] = "hdr" if enabled else "srgb"
    if enabled and output == "DP-2":
        monitor["hdr_tuning"] = {
            "sdrbrightness": 1.2,
            "sdrsaturation": 0.98,
            "sdr_eotf": "srgb",
            "sdr_min_luminance": 0.25,
            "sdr_max_luminance": 480,
            "min_luminance": 0.25,
            "max_luminance": 480,
            "max_avg_luminance": 302,
        }
    elif not enabled:
        monitor.pop("hdr_tuning", None)
    validate_settings(settings)
    atomic_json(settings_path(), settings)
    return settings


def theme_manifests() -> list[dict[str, Any]]:
    manifests = []
    for path in sorted((ROOT / "themes").glob("*/manifest.json")):
        manifests.append(json.loads(path.read_text()))
    return manifests


class ThemeManager:
    def __init__(self, root: Path = ROOT, state: Path = STATE):
        self.root, self.state = root, state

    def manifest(self, slug: str) -> dict[str, Any]:
        path = self.root / "themes" / slug / "manifest.json"
        if not path.exists():
            raise ValueError(f"unknown theme: {slug}")
        manifest = json.loads(path.read_text())
        if manifest["schema_version"] != 1 or manifest["slug"] != slug:
            raise ValueError(f"invalid theme manifest: {slug}")
        return manifest

    def apply(
        self,
        slug: str,
        preview: bool = False,
        preview_timeout: int = 20,
    ) -> dict[str, Any]:
        manifest = self.manifest(slug)
        wallpaper = self.root / "themes" / slug / manifest["wallpaper"]["file"]
        checksum = hashlib.sha256(wallpaper.read_bytes()).hexdigest()
        if checksum != manifest["wallpaper"]["sha256"]:
            raise ValueError(f"wallpaper checksum mismatch: {slug}")
        generated = self.state / "generated"
        current = generated / "theme.json"
        previous = self.state / "previous-theme.json"
        old = json.loads(current.read_text()) if current.exists() else None
        self.state.mkdir(parents=True, exist_ok=True)
        stage = Path(tempfile.mkdtemp(prefix=".theme-generation-", dir=self.state))
        try:
            atomic_json(stage / "theme.json", manifest)
            self._write_generated(manifest, wallpaper, stage)
            self._publish_generation(stage)
        except BaseException:
            if stage.exists():
                shutil.rmtree(stage)
            raise
        if old and old.get("slug") != slug:
            atomic_json(previous, old)
        status = {
            "slug": slug,
            "preview": preview,
            "applied_at": int(time.time()),
        }
        if preview:
            status["token"] = hashlib.md5(
                os.urandom(32), usedforsecurity=False
            ).hexdigest()
            status["timeout"] = preview_timeout
        atomic_json(self.state / "theme-status.json", status)
        if self._is_live_state():
            if not preview:
                self._update_settings(slug)
            self._notify_reload(manifest)
            if preview:
                subprocess.Popen(
                    [
                        sys.executable,
                        str(Path(__file__).resolve()),
                        "_theme-timeout",
                        str(status["token"]),
                        str(preview_timeout),
                    ],
                    start_new_session=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
        return manifest

    def expire_preview(self, token: str) -> bool:
        status_path = self.state / "theme-status.json"
        if not status_path.exists():
            return False
        status = json.loads(status_path.read_text())
        if not status.get("preview") or status.get("token") != token:
            return False
        self.rollback()
        return True

    def _publish_generation(self, stage: Path) -> None:
        generated = self.state / "generated"
        old = self.state / f".theme-previous-{os.getpid()}"
        if old.exists() or old.is_symlink():
            if old.is_dir() and not old.is_symlink():
                shutil.rmtree(old)
            else:
                old.unlink()
        had_current = generated.exists() or generated.is_symlink()
        if had_current:
            os.replace(generated, old)
        try:
            os.replace(stage, generated)
        except BaseException:
            if had_current:
                os.replace(old, generated)
            raise
        if had_current:
            if old.is_dir() and not old.is_symlink():
                shutil.rmtree(old)
            else:
                old.unlink(missing_ok=True)

    def _update_settings(self, slug: str) -> None:
        config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
        path = config / "colutti-desktop/settings.json"
        settings = json.loads(path.read_text()) if path.exists() else default_settings()
        settings["theme"] = slug
        settings["theme_override"] = True
        validate_settings(settings)
        atomic_json(path, settings)

    def _write_generated(
        self,
        manifest: dict[str, Any],
        wallpaper: Path,
        generated: Path | None = None,
    ) -> None:
        palette = manifest["palette"]
        panel = manifest["panel"]
        generated = generated or self.state / "generated"
        personality = {
            "islands": {"radius": 14, "width": 48, "padding": 20, "opacity": 0.96},
            "rail": {"radius": 4, "width": 52, "padding": 16, "opacity": 0.82},
            "studio": {"radius": 8, "width": 46, "padding": 18, "opacity": 0.98},
            "architect": {"radius": 3, "width": 50, "padding": 24, "opacity": 1.0},
            "canopy": {"radius": 18, "width": 48, "padding": 22, "opacity": 0.94},
        }[panel["layout"]]

        def rgb(token: str) -> str:
            value = token.lstrip("#")
            return ",".join(str(int(value[index:index + 2], 16)) for index in (0, 2, 4))

        def kde_group(name: str, background: str, alternate: str, foreground: str) -> str:
            return (
                f"[{name}]\n"
                f"BackgroundAlternate={rgb(alternate)}\n"
                f"BackgroundNormal={rgb(background)}\n"
                f'DecorationFocus={rgb(palette["accent"])}\n'
                f'DecorationHover={rgb(palette["accent"])}\n'
                f'ForegroundActive={rgb(palette["accent"])}\n'
                f'ForegroundInactive={rgb(palette["muted"])}\n'
                f'ForegroundLink={rgb(palette["accent"])}\n'
                f'ForegroundNegative={rgb(palette["critical"])}\n'
                f'ForegroundNeutral={rgb(palette["warning"])}\n'
                f"ForegroundNormal={rgb(foreground)}\n"
                f'ForegroundPositive={rgb(palette["success"])}\n'
                f'ForegroundVisited={rgb(palette["accent_alt"])}\n\n'
            )
        atomic_text(
            generated / "alacritty-theme.toml",
            "[colors.primary]\n"
            f'background = "{palette["background"]}"\n'
            f'foreground = "{palette["text"]}"\n\n'
            "[colors.normal]\n"
            f'black = "{palette["background"]}"\n'
            f'red = "{palette["critical"]}"\n'
            f'green = "{palette["success"]}"\n'
            f'yellow = "{palette["warning"]}"\n'
            f'blue = "{palette["accent_alt"]}"\n'
            f'magenta = "{palette["accent_alt"]}"\n'
            f'cyan = "{palette["accent"]}"\n'
            f'white = "{palette["text"]}"\n',
        )
        atomic_text(
            generated / "fuzzel-theme.ini",
            "[colors]\n"
            f'background={palette["background"].lstrip("#")}f2\n'
            f'text={palette["text"].lstrip("#")}ff\n'
            f'prompt={palette["accent"].lstrip("#")}ff\n'
            f'placeholder={palette["muted"].lstrip("#")}ff\n'
            f'input={palette["text"].lstrip("#")}ff\n'
            f'match={palette["accent_alt"].lstrip("#")}ff\n'
            f'selection={palette["surface_alt"].lstrip("#")}ff\n'
            f'selection-text={palette["text"].lstrip("#")}ff\n'
            f'selection-match={palette["accent"].lstrip("#")}ff\n'
            f'border={palette["accent"].lstrip("#")}ff\n\n'
            "[main]\n"
            f'width={personality["width"]}\n'
            f'horizontal-pad={personality["padding"]}\n\n'
            "[border]\n"
            f'radius={personality["radius"]}\n',
        )
        atomic_text(
            generated / "swaync-theme.css",
            f'@define-color background {palette["background"]};\n'
            f'@define-color surface {palette["surface"]};\n'
            f'@define-color surface_alt {palette["surface_alt"]};\n'
            f'@define-color text {palette["text"]};\n'
            f'@define-color muted {palette["muted"]};\n'
            f'@define-color accent {palette["accent"]};\n'
            f'@define-color warning {palette["warning"]};\n'
            f'@define-color critical {palette["critical"]};\n'
            f'@define-color outline {palette["outline"]};\n'
            "window.control-center {\n"
            f'  border-radius: {personality["radius"] + 4}px;\n'
            f'  background: alpha(@background, {personality["opacity"]});\n'
            "}\n"
            "window.control-center .widget-dnd,\n"
            "window.control-center .widget-volume,\n"
            "window.control-center .widget-mpris,\n"
            "window.control-center .widget-buttons-grid {\n"
            f'  border-radius: {personality["radius"]}px;\n'
            "}\n"
            "window.notification-window .notification {\n"
            f'  border-radius: {personality["radius"]}px;\n'
            "}\n",
        )
        atomic_text(
            generated / "gtk-theme.css",
            f'@define-color theme_bg_color {palette["background"]};\n'
            f'@define-color theme_fg_color {palette["text"]};\n'
            f'@define-color theme_base_color {palette["background"]};\n'
            f'@define-color theme_text_color {palette["text"]};\n'
            f'@define-color theme_selected_bg_color {palette["accent"]};\n'
            f'@define-color theme_selected_fg_color {palette["background"]};\n'
            f'@define-color accent_bg_color {palette["accent"]};\n'
            f'@define-color accent_fg_color {palette["background"]};\n'
            f'@define-color window_bg_color {palette["background"]};\n'
            f'@define-color window_fg_color {palette["text"]};\n'
            f'@define-color view_bg_color {palette["background"]};\n'
            f'@define-color view_fg_color {palette["text"]};\n'
            f'@define-color headerbar_bg_color {palette["surface"]};\n'
            f'@define-color headerbar_fg_color {palette["text"]};\n'
            f'@define-color card_bg_color {palette["surface"]};\n'
            f'@define-color card_fg_color {palette["text"]};\n'
            f'@define-color borders {palette["outline"]};\n'
            f'@define-color error_bg_color {palette["critical"]};\n'
            f'@define-color warning_bg_color {palette["warning"]};\n'
            f'@define-color success_bg_color {palette["success"]};\n',
        )
        vscode_theme = {
            "name": f"Colutti Current ({manifest['name']})",
            "type": manifest["mode"],
            "colors": {
                "activityBar.background": palette["surface"],
                "activityBar.foreground": palette["text"],
                "activityBarBadge.background": palette["accent"],
                "activityBarBadge.foreground": palette["background"],
                "badge.background": palette["accent"],
                "badge.foreground": palette["background"],
                "button.background": palette["accent"],
                "button.foreground": palette["background"],
                "editor.background": palette["background"],
                "editor.foreground": palette["text"],
                "editorCursor.foreground": palette["accent"],
                "editorGroupHeader.tabsBackground": palette["surface"],
                "editorLineNumber.foreground": palette["muted"],
                "editorLineNumber.activeForeground": palette["accent"],
                "focusBorder": palette["accent"],
                "input.background": palette["surface"],
                "input.foreground": palette["text"],
                "input.border": palette["outline"],
                "list.activeSelectionBackground": palette["surface_alt"],
                "list.activeSelectionForeground": palette["text"],
                "panel.background": palette["surface"],
                "panel.border": palette["outline"],
                "sideBar.background": palette["surface"],
                "sideBar.foreground": palette["text"],
                "statusBar.background": palette["surface_alt"],
                "statusBar.foreground": palette["text"],
                "tab.activeBackground": palette["background"],
                "tab.activeForeground": palette["text"],
                "tab.inactiveBackground": palette["surface"],
                "tab.inactiveForeground": palette["muted"],
                "terminal.background": palette["background"],
                "terminal.foreground": palette["text"],
                "titleBar.activeBackground": palette["surface"],
                "titleBar.activeForeground": palette["text"],
            },
            "tokenColors": [
                {
                    "scope": ["comment", "punctuation.definition.comment"],
                    "settings": {"foreground": palette["muted"], "fontStyle": "italic"},
                },
                {
                    "scope": ["keyword", "storage", "entity.name.tag"],
                    "settings": {"foreground": palette["accent"]},
                },
                {
                    "scope": ["string", "constant.numeric", "constant.language"],
                    "settings": {"foreground": palette["accent_alt"]},
                },
                {
                    "scope": ["entity.name.function", "support.function"],
                    "settings": {"foreground": palette["success"]},
                },
            ],
        }
        atomic_json(generated / "vscodium-theme.json", vscode_theme)
        kde_scheme = (
            kde_group("Colors:Button", palette["surface"], palette["surface_alt"], palette["text"])
            + kde_group("Colors:Complementary", palette["background"], palette["surface"], palette["text"])
            + kde_group("Colors:Header", palette["surface"], palette["surface_alt"], palette["text"])
            + kde_group("Colors:Header][Inactive", palette["background"], palette["surface"], palette["muted"])
            + kde_group("Colors:Tooltip", palette["surface"], palette["surface_alt"], palette["text"])
            + kde_group("Colors:View", palette["background"], palette["surface"], palette["text"])
            + kde_group("Colors:Window", palette["surface"], palette["surface_alt"], palette["text"])
            + kde_group("Colors:Selection", palette["accent"], palette["accent_alt"], palette["background"])
            + "[General]\n"
            "ColorScheme=ColuttiCurrent\n"
            f'Name=Colutti Current ({manifest["name"]})\n'
            "shadeSortColumn=true\n\n"
            "[KDE]\ncontrast=4\n\n"
            "[WM]\n"
            f'activeBackground={rgb(palette["surface_alt"])}\n'
            f'activeBlend={rgb(palette["text"])}\n'
            f'activeForeground={rgb(palette["text"])}\n'
            f'inactiveBackground={rgb(palette["surface"])}\n'
            f'inactiveBlend={rgb(palette["muted"])}\n'
            f'inactiveForeground={rgb(palette["muted"])}\n'
        )
        atomic_text(generated / "ColuttiCurrent.colors", kde_scheme)
        atomic_text(
            generated / "hyprpaper.conf",
            "ipc = on\n"
            "splash = false\n"
            "wallpaper {\n"
            "    monitor = DP-2\n"
            f"    path = {wallpaper}\n"
            "    fit_mode = cover\n"
            "}\n"
            "wallpaper {\n"
            "    monitor = HDMI-A-1\n"
            f"    path = {wallpaper}\n"
            "    fit_mode = cover\n"
            "}\n",
        )
        atomic_text(
            generated / "hyprland-theme.lua",
            "hl.config({ general = { col = { "
            f'active_border = "rgba({palette["accent"].lstrip("#")}ff)", '
            f'inactive_border = "rgba({palette["outline"].lstrip("#")}aa)" '
            "} } })\n",
        )
        atomic_text(
            generated / "hyprlock-theme.conf",
            f"$background = rgb({palette['background'].lstrip('#')})\n"
            f"$text = rgb({palette['text'].lstrip('#')})\n"
            f"$accent = rgb({palette['accent'].lstrip('#')})\n"
            f"$success = rgb({palette['success'].lstrip('#')})\n"
            f"$critical = rgb({palette['critical'].lstrip('#')})\n",
        )

    def rollback(self) -> dict[str, Any]:
        previous = self.state / "previous-theme.json"
        if not previous.exists():
            raise ValueError("no previous theme")
        manifest = json.loads(previous.read_text())
        return self.apply(manifest["slug"])

    def _is_live_state(self) -> bool:
        account_home = Path(pwd.getpwuid(os.getuid()).pw_dir)
        return (
            self.state.resolve() == STATE.resolve()
            and Path.home().resolve() == account_home.resolve()
        )

    def _install_vscodium_theme(self) -> None:
        extension = (
            Path.home()
            / ".vscode-oss/extensions/colutti-desktop-theme/themes"
        )
        if not extension.parent.exists():
            return
        extension.mkdir(parents=True, exist_ok=True)
        source = self.state / "generated/vscodium-theme.json"
        destination = extension / "colutti-current.json"
        if destination.exists() or destination.is_symlink():
            destination.unlink()
        destination.symlink_to(source)
        settings_path = (
            Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
            / "VSCodium/User/settings.json"
        )
        if not settings_path.exists():
            return
        content = settings_path.read_text()
        updated, replacements = re.subn(
            r'("workbench\.colorTheme"\s*:\s*)"[^"]*"',
            r'\1"Colutti Current"',
            content,
            count=1,
        )
        if replacements == 0:
            closing = updated.rfind("}")
            if closing < 0:
                raise ValueError("VSCodium settings are not a JSON object")
            prefix = updated[:closing].rstrip()
            separator = "" if prefix.endswith(("{", ",")) else ","
            updated = (
                prefix
                + separator
                + '\n    "workbench.colorTheme": "Colutti Current"\n'
                + updated[closing:]
            )
        atomic_text(settings_path, updated)

    def _apply_desktop_preferences(self, manifest: dict[str, Any]) -> None:
        mode = manifest["mode"]
        icon_theme = manifest["icon_theme"]
        cursor_theme = manifest["cursor_theme"]
        font = manifest["font"]
        if shutil.which("gsettings"):
            values = {
                "color-scheme": "prefer-dark" if mode == "dark" else "prefer-light",
                "gtk-theme": "Adwaita-dark" if mode == "dark" else "Adwaita",
                "icon-theme": icon_theme,
                "cursor-theme": cursor_theme,
                "font-name": f"{font} 11",
            }
            for key, value in values.items():
                subprocess.run(
                    [
                        "gsettings",
                        "set",
                        "org.gnome.desktop.interface",
                        key,
                        value,
                    ],
                    check=False,
                    capture_output=True,
                )
        if shutil.which("kwriteconfig6"):
            for group, key, value in (
                ("Icons", "Theme", icon_theme),
                ("General", "font", f"{font},11,-1,5,50,0,0,0,0,0"),
                ("KDE", "widgetStyle", "Breeze"),
            ):
                subprocess.run(
                    [
                        "kwriteconfig6",
                        "--file",
                        "kdeglobals",
                        "--group",
                        group,
                        "--key",
                        key,
                        value,
                    ],
                    check=False,
                    capture_output=True,
                )
        if shutil.which("plasma-apply-cursortheme"):
            subprocess.run(
                ["plasma-apply-cursortheme", cursor_theme],
                check=False,
                capture_output=True,
            )
        self._install_vscodium_theme()

    def _notify_reload(self, manifest: dict[str, Any]) -> None:
        if shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
            subprocess.run(["hyprctl", "reload"], check=False, capture_output=True)
        wallpaper = (
            self.root
            / "themes"
            / manifest["slug"]
            / manifest["wallpaper"]["file"]
        )
        paper_updated = False
        if shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
            available = subprocess.run(
                ["hyprctl", "hyprpaper", "listactive"],
                check=False,
                capture_output=True,
            )
            if available.returncode == 0:
                results = [
                    subprocess.run(
                        [
                            "hyprctl",
                            "hyprpaper",
                            "wallpaper",
                            f"{output}, {wallpaper}, cover",
                        ],
                        check=False,
                        capture_output=True,
                    )
                    for output in ("DP-2", "HDMI-A-1")
                ]
                paper_updated = all(result.returncode == 0 for result in results)
        if not paper_updated and shutil.which("systemctl"):
            subprocess.run(
                ["systemctl", "--user", "reset-failed", "hyprpaper.service"],
                check=False,
                capture_output=True,
            )
            subprocess.run(
                ["systemctl", "--user", "restart", "hyprpaper.service"],
                check=False,
                capture_output=True,
            )
        if shutil.which("swaync-client"):
            subprocess.run(
                ["swaync-client", "--reload-css"],
                check=False,
                capture_output=True,
            )
        if shutil.which("plasma-apply-colorscheme"):
            generated = STATE / "generated/ColuttiCurrent.colors"
            color_dir = Path(
                os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share")
            ) / "color-schemes"
            color_dir.mkdir(parents=True, exist_ok=True)
            installed = color_dir / "ColuttiCurrent.colors"
            shutil.copy2(generated, installed)
            subprocess.run(
                ["plasma-apply-colorscheme", "ColuttiCurrent"],
                check=False,
                capture_output=True,
            )
        self._apply_desktop_preferences(manifest)


class MonitorManager:
    def __init__(self, root: Path = ROOT, state: Path = STATE):
        self.root, self.state = root, state

    @staticmethod
    def _expression(output: str, monitor: dict[str, Any]) -> str:
        expression = (
            "hl.monitor({ "
            f"output = {json.dumps(output)}, "
            f"mode = {json.dumps(monitor['mode'])}, "
            f"position = {json.dumps(monitor['position'])}, "
            f"scale = {float(monitor['scale'])!r}, "
            f"bitdepth = {int(monitor['bitdepth'])}, "
            f"cm = {json.dumps(monitor['color_mode'])}, "
            f"vrr = {int(bool(monitor.get('vrr', False)))} "
            ""
        )
        tuning = monitor.get("hdr_tuning", {})
        for key, value in tuning.items():
            expression += f", {key} = {json.dumps(value)}"
        return expression + " })"

    @classmethod
    def _apply_one(
        cls,
        output: str,
        monitor: dict[str, Any],
        *,
        check: bool,
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            ["hyprctl", "eval", cls._expression(output, monitor)],
            text=True,
            capture_output=True,
            check=check,
        )

    @staticmethod
    def _capture_current() -> dict[str, dict[str, Any]]:
        result = subprocess.run(
            ["hyprctl", "monitors", "-j"],
            text=True,
            capture_output=True,
            check=True,
        )
        monitors: dict[str, dict[str, Any]] = {}
        for output in json.loads(result.stdout):
            pixel_format = str(output.get("currentFormat", "")).upper()
            bitdepth = 10 if "101010" in pixel_format or pixel_format in {"XR30", "AR30"} else 8
            color_mode = (
                output.get("colorManagementPreset")
                or output.get("cm")
                or "srgb"
            )
            monitors[output["name"]] = {
                "mode": (
                    f"{int(output['width'])}x{int(output['height'])}"
                    f"@{float(output['refreshRate']):.2f}"
                ),
                "position": f"{int(output['x'])}x{int(output['y'])}",
                "scale": float(output["scale"]),
                "bitdepth": bitdepth,
                "color_mode": color_mode,
                "vrr": bool(output.get("vrr", False)),
            }
            tuning = {
                "sdrbrightness": output.get("sdrBrightness"),
                "sdrsaturation": output.get("sdrSaturation"),
                "sdr_min_luminance": output.get("sdrMinLuminance"),
                "sdr_max_luminance": output.get("sdrMaxLuminance"),
            }
            if all(value is not None for value in tuning.values()):
                monitors[output["name"]]["hdr_tuning"] = tuning
        if not monitors:
            raise ValueError("Hyprland reported no active monitors")
        return monitors

    def _restore(self, monitors: dict[str, dict[str, Any]]) -> None:
        for output, monitor in monitors.items():
            self._apply_one(output, monitor, check=False)

    def _restore_previous_settings(self) -> None:
        previous = self.state / "previous-settings.json"
        if not previous.exists():
            return
        settings = json.loads(previous.read_text())
        validate_settings(settings)
        atomic_json(settings_path(), settings)
        previous.unlink()

    @staticmethod
    def _matches_current(
        target: dict[str, Any], current: dict[str, Any] | None
    ) -> bool:
        if current is None:
            return False
        target_width_height, target_refresh = str(target["mode"]).split("@", 1)
        current_width_height, current_refresh = str(current["mode"]).split("@", 1)
        return (
            target_width_height == current_width_height
            and abs(float(target_refresh) - float(current_refresh)) < 0.01
            and abs(float(target["scale"]) - float(current["scale"])) < 0.001
            and int(target["bitdepth"]) == int(current["bitdepth"])
            and target["color_mode"] == current["color_mode"]
            and bool(target.get("vrr", False)) == bool(current.get("vrr", False))
            and target.get("hdr_tuning", {}) == current.get("hdr_tuning", {})
        )

    def apply(self, timeout: int = 20, execute: bool = True) -> str:
        settings = read_settings()
        token = hashlib.md5(os.urandom(32), usedforsecurity=False).hexdigest()
        pending = {
            "token": token,
            "timeout": timeout,
            "created_at": int(time.time()),
            "monitors": settings["monitors"],
        }
        if execute and shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
            current = self._capture_current()
            atomic_json(self.state / "last-valid-monitors.json", current)
            pending["previous_monitors"] = current
        atomic_json(self.state / "pending-monitor.json", pending)
        if execute and shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
            try:
                for output, monitor in settings["monitors"].items():
                    if not self._matches_current(
                        monitor, pending["previous_monitors"].get(output)
                    ):
                        self._apply_one(output, monitor, check=True)
            except subprocess.CalledProcessError:
                self._restore(pending["previous_monitors"])
                (self.state / "pending-monitor.json").unlink(missing_ok=True)
                self._restore_previous_settings()
                raise
            subprocess.Popen(
                [
                    sys.executable, str(Path(__file__).resolve()),
                    "_monitor-timeout", token, str(timeout),
                ],
                start_new_session=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        return token

    def confirm(self, token: str) -> None:
        pending = self.state / "pending-monitor.json"
        if not pending.exists():
            raise ValueError("no pending monitor transaction")
        transaction = json.loads(pending.read_text())
        if transaction["token"] != token:
            raise ValueError("invalid monitor confirmation token")
        atomic_json(self.state / "last-valid-monitors.json", transaction["monitors"])
        pending.unlink()
        (self.state / "previous-settings.json").unlink(missing_ok=True)

    def rollback(self) -> None:
        pending = self.state / "pending-monitor.json"
        if pending.exists():
            pending.unlink()
        self._restore_previous_settings()
        valid = self.state / "last-valid-monitors.json"
        if not valid.exists():
            return
        if shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
            self._restore(json.loads(valid.read_text()))

    def hdr(self, action: str) -> dict[str, Any]:
        settings = read_settings()
        capable = {
            output: monitor
            for output, monitor in settings["monitors"].items()
            if monitor["hdr_fullscreen_passthrough"]
        }
        if not capable:
            raise ValueError("no monitor is configured for HDR")
        if action == "status":
            current = self._capture_current()
            enabled = [
                output
                for output in capable
                if output in current
                and current[output]["bitdepth"] == 10
                and current[output]["color_mode"] in {"hdr", "hdredid"}
            ]
            return {
                "state": "on" if set(enabled) == set(capable) else "off",
                "monitors": enabled,
            }
        if not shutil.which("hyprctl") or not os.environ.get(
            "HYPRLAND_INSTANCE_SIGNATURE"
        ):
            raise ValueError("Hyprland is not active")
        for output, configured in capable.items():
            monitor = dict(configured)
            if action == "on":
                monitor.update({"bitdepth": 10, "color_mode": "hdr"})
            self._apply_one(output, monitor, check=True)
        return {"state": action, "monitors": sorted(capable)}


def command_status(command: str) -> str:
    return "ok" if shutil.which(command) else "missing"


def service_check(name: str, unit: str) -> dict[str, Any]:
    if not shutil.which("systemctl"):
        return {"name": name, "status": "missing", "detail": "systemctl unavailable"}
    result = subprocess.run(
        ["systemctl", "--user", "is-active", unit],
        text=True,
        capture_output=True,
        check=False,
    )
    state = result.stdout.strip() or "unknown"
    return {
        "name": name,
        "status": "ok" if result.returncode == 0 and state == "active" else "error",
        "detail": state,
    }


def bus_owner_check(name: str, bus_name: str) -> dict[str, Any]:
    if not shutil.which("busctl"):
        return {"name": name, "status": "missing", "detail": "busctl unavailable"}
    result = subprocess.run(
        ["busctl", "--user", "status", bus_name],
        text=True,
        capture_output=True,
        check=False,
    )
    return {
        "name": name,
        "status": "ok" if result.returncode == 0 else "error",
        "detail": bus_name,
    }


def hypr_json(command: str) -> Any:
    result = subprocess.run(
        ["hyprctl", command, "-j"],
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise ValueError(result.stderr.strip() or f"hyprctl {command} failed")
    return json.loads(result.stdout)


def monitor_layout_check(settings: dict[str, Any]) -> dict[str, Any]:
    try:
        live = {monitor["name"]: monitor for monitor in hypr_json("monitors")}
    except (ValueError, json.JSONDecodeError) as error:
        return {"name": "monitor-layout", "status": "error", "detail": str(error)}
    mismatches = []
    for output, expected in settings["monitors"].items():
        actual = live.get(output)
        if actual is None:
            mismatches.append(f"{output}: missing")
            continue
        width, height = map(int, expected["mode"].split("@", 1)[0].split("x"))
        x, y = map(int, expected["position"].split("x"))
        pixel_format = str(actual.get("currentFormat", "")).upper()
        bitdepth = 10 if "101010" in pixel_format or pixel_format in {"XR30", "AR30"} else 8
        color_mode = actual.get("colorManagementPreset") or "srgb"
        comparisons = {
            "mode": (actual.get("width"), actual.get("height"), width, height),
            "position": (actual.get("x"), actual.get("y"), x, y),
            "scale": (float(actual.get("scale", 0)), float(expected["scale"])),
            "bitdepth": (bitdepth, int(expected["bitdepth"])),
            "color": (color_mode, expected["color_mode"]),
            "vrr": (bool(actual.get("vrr", False)), False),
        }
        if comparisons["mode"][:2] != comparisons["mode"][2:]:
            mismatches.append(f"{output}: mode")
        if comparisons["position"][:2] != comparisons["position"][2:]:
            mismatches.append(f"{output}: position")
        if abs(comparisons["scale"][0] - comparisons["scale"][1]) > 0.01:
            mismatches.append(f"{output}: scale")
        for key in ("bitdepth", "color", "vrr"):
            if comparisons[key][0] != comparisons[key][1]:
                mismatches.append(f"{output}: {key}")
    return {
        "name": "monitor-layout",
        "status": "ok" if not mismatches else "error",
        "detail": mismatches,
    }


def primary_panel_check() -> dict[str, Any]:
    try:
        layers = hypr_json("layers")
    except (ValueError, json.JSONDecodeError) as error:
        return {"name": "primary-panel", "status": "error", "detail": str(error)}
    counts = {}
    for output, data in layers.items():
        counts[output] = sum(
            layer.get("namespace") == "quickshell"
            for level in data.get("levels", {}).values()
            for layer in level
        )
    valid = counts.get("DP-2") == 1 and counts.get("HDMI-A-1", 0) == 0
    return {
        "name": "primary-panel",
        "status": "ok" if valid else "error",
        "detail": counts,
    }


def audio_defaults_check() -> dict[str, Any]:
    details = {}
    expected = {
        "sink": ("@DEFAULT_AUDIO_SINK@", "iFi"),
        "source": ("@DEFAULT_AUDIO_SOURCE@", "HyperX SoloCast"),
    }
    valid = True
    for kind, (target, label) in expected.items():
        result = subprocess.run(
            ["wpctl", "inspect", target],
            text=True,
            capture_output=True,
            check=False,
        )
        description = next(
            (
                line.split("=", 1)[1].strip().strip('"')
                for line in result.stdout.splitlines()
                if "node.description =" in line
            ),
            "",
        )
        details[kind] = description
        valid = valid and result.returncode == 0 and label in description
    return {
        "name": "audio-defaults",
        "status": "ok" if valid else "error",
        "detail": details,
    }


def restored_apps_check() -> dict[str, Any]:
    try:
        monitors = {item["id"]: item["name"] for item in hypr_json("monitors")}
        clients = hypr_json("clients")
    except (ValueError, json.JSONDecodeError) as error:
        return {"name": "restored-apps", "status": "error", "detail": str(error)}
    expected = {
        "zen": ("app.zen_browser.zen", None, 1, "DP-2"),
        "alacritty": ("Alacritty", None, 2, "DP-2"),
        "steam": ("steam", "Steam", 4, "DP-2"),
        "telegram": ("org.telegram.desktop", None, 6, "HDMI-A-1"),
        "discord": ("discord", None, 6, "HDMI-A-1"),
    }
    mismatches = []
    for name, (app_class, title, workspace, output) in expected.items():
        matches = [
            client for client in clients
            if str(client.get("class", "")).lower() == app_class.lower()
            and (title is None or client.get("title") == title)
        ]
        if not matches:
            mismatches.append(f"{name}: missing")
            continue
        client = matches[0]
        if (
            client.get("workspace", {}).get("id") != workspace
            or monitors.get(client.get("monitor")) != output
            or client.get("floating") is not False
        ):
            mismatches.append(f"{name}: placement")
    return {
        "name": "restored-apps",
        "status": "ok" if not mismatches else "error",
        "detail": mismatches,
    }


def storage_headroom_check() -> dict[str, Any]:
    usage = shutil.disk_usage("/")
    free_gib = usage.free / (1024 ** 3)
    used_percent = round(usage.used * 100 / usage.total)
    return {
        "name": "storage-headroom",
        "status": "ok" if free_gib >= 50 else ("warning" if free_gib >= 20 else "error"),
        "detail": {
            "free_gib": round(free_gib, 1),
            "used_percent": used_percent,
        },
    }


def gamemode_group_check() -> dict[str, Any]:
    try:
        group = grp.getgrnam("gamemode")
    except KeyError:
        return {
            "name": "gamemode-group",
            "status": "error",
            "detail": "group missing",
        }
    member = group.gr_gid in os.getgroups()
    return {
        "name": "gamemode-group",
        "status": "ok" if member else "error",
        "detail": {
            "group": group.gr_name,
            "member": member,
            "requires_new_login": not member,
        },
    }


def doctor() -> tuple[dict[str, Any], int]:
    required = [
        "Hyprland",
        "qs",
        "uwsm",
        "hyprctl",
        "wpctl",
        "grim",
        "slurp",
        "fuzzel",
        "swaync-client",
        "hyprsunset",
    ]
    checks = [{"name": command, "status": command_status(command)} for command in required]
    checks.extend([
        service_check("uwsm-session", "wayland-wm@Hyprland.service"),
        service_check("shell", "colutti-quickshell.service"),
        service_check("wallpaper", "hyprpaper.service"),
        service_check("idle", "hypridle.service"),
        service_check("sunset", "hyprsunset.service"),
        service_check("clipboard", "colutti-clipboard.service"),
        service_check("notifications", "swaync.service"),
        service_check("polkit-agent", "plasma-polkit-agent.service"),
        service_check("portal-frontend", "xdg-desktop-portal.service"),
        service_check("portal-hyprland", "xdg-desktop-portal-hyprland.service"),
        service_check("portal-kde", "plasma-xdg-desktop-portal-kde.service"),
        bus_owner_check("notification-service", "org.freedesktop.Notifications"),
        storage_headroom_check(),
        gamemode_group_check(),
    ])
    try:
        settings = read_settings()
        checks.extend([
            monitor_layout_check(settings),
            primary_panel_check(),
            audio_defaults_check(),
            restored_apps_check(),
        ])
        generated_path = STATE / "generated/theme.json"
        generated = json.loads(generated_path.read_text())
        match = settings["theme"] == generated["slug"]
        checks.append({
            "name": "theme-state",
            "status": "ok" if match else "error",
            "detail": {
                "settings": settings["theme"],
                "generated": generated["slug"],
            },
        })
    except (KeyError, OSError, ValueError, json.JSONDecodeError) as error:
        checks.append({
            "name": "theme-state",
            "status": "error",
            "detail": str(error),
        })
    manifest = json.loads((ROOT / "packages.json").read_text())
    installed_packages: set[str] = set()
    if shutil.which("pacman"):
        installed = subprocess.run(
            ["pacman", "-Qq"],
            text=True,
            capture_output=True,
            check=False,
        )
        installed_packages = set(installed.stdout.splitlines())
    missing_packages = sorted(
        set(manifest["install"]) - installed_packages
    )
    checks.append({
        "name": "official-packages",
        "status": "ok" if not missing_packages else "error",
        "detail": missing_packages,
    })
    missing_flatpaks = []
    for application in manifest.get("flatpak_apps", []):
        result = subprocess.run(
            ["flatpak", "info", application],
            text=True,
            capture_output=True,
            check=False,
        ) if shutil.which("flatpak") else None
        if result is None or result.returncode != 0:
            missing_flatpaks.append(application)
    checks.append({
        "name": "flatpak-apps",
        "status": "ok" if not missing_flatpaks else "error",
        "detail": missing_flatpaks,
    })
    foreign = subprocess.run(
        ["pacman", "-Qm"], text=True, capture_output=True, check=False
    ) if shutil.which("pacman") else None
    checks.append({
        "name": "foreign-packages",
        "status": "ok" if foreign and not foreign.stdout.strip() else "warning",
        "detail": [] if foreign is None else foreign.stdout.splitlines(),
    })
    if shutil.which("systemctl"):
        failed = subprocess.run(
            ["systemctl", "--user", "--failed", "--no-legend", "--plain"],
            text=True,
            capture_output=True,
            check=False,
        )
        failed_units = [
            line.split()[0] for line in failed.stdout.splitlines() if line.split()
        ]
        checks.append({
            "name": "failed-user-units",
            "status": "ok" if not failed_units else "warning",
            "detail": failed_units,
        })
    report = {"schema_version": 1, "checks": checks}
    return report, 0 if all(c["status"] == "ok" for c in checks) else 2


def set_game_profile(action: str) -> dict[str, Any]:
    path = STATE / "game-profile.json"
    current = json.loads(path.read_text()) if path.exists() else {"state": "off"}
    if action == "status":
        return current
    if action == current.get("state"):
        return current
    previous_power = current.get("previous_power", "balanced")
    target_power = previous_power
    if shutil.which("powerprofilesctl"):
        if action == "on":
            result = subprocess.run(
                ["powerprofilesctl", "get"],
                text=True,
                capture_output=True,
                check=False,
            )
            if result.returncode == 0 and result.stdout.strip():
                previous_power = result.stdout.strip()
            target_power = "performance"
        subprocess.run(
            ["powerprofilesctl", "set", target_power],
            check=False,
        )
    previous_animations = bool(current.get("previous_animations", True))
    previous_blur = bool(current.get("previous_blur", True))
    if shutil.which("hyprctl") and os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        if action == "on":
            for option, field in (
                ("animations:enabled", "animations"),
                ("decoration:blur:enabled", "blur"),
            ):
                result = subprocess.run(
                    ["hyprctl", "getoption", option, "-j"],
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if result.returncode == 0:
                    try:
                        value = bool(json.loads(result.stdout)["bool"])
                        if field == "animations":
                            previous_animations = value
                        else:
                            previous_blur = value
                    except (KeyError, json.JSONDecodeError):
                        pass
        animations = False if action == "on" else previous_animations
        blur = False if action == "on" else previous_blur
        expression = (
            "hl.config({ animations = { enabled = "
            + str(animations).lower()
            + " }, decoration = { blur = { enabled = "
            + str(blur).lower()
            + " } } })"
        )
        subprocess.run(["hyprctl", "eval", expression], check=False, capture_output=True)
    previous_dnd = current.get("previous_dnd", False)
    if shutil.which("swaync-client"):
        if action == "on":
            result = subprocess.run(
                ["swaync-client", "-D"], text=True, capture_output=True, check=False
            )
            previous_dnd = result.stdout.strip().lower() == "true"
        subprocess.run(
            ["swaync-client", "-dn" if action == "on" or previous_dnd else "-df"],
            check=False,
            capture_output=True,
        )
    if shutil.which("systemctl"):
        subprocess.run(
            [
                "systemctl",
                "--user",
                "start" if action == "on" else "stop",
                "colutti-game-inhibit.service",
            ],
            check=False,
            capture_output=True,
        )
    profile = {
        "state": action,
        "previous_power": previous_power,
        "previous_dnd": previous_dnd,
        "previous_animations": previous_animations,
        "previous_blur": previous_blur,
        "changed_at": int(time.time()),
    }
    atomic_json(path, profile)
    config = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    settings_path = config / "colutti-desktop/settings.json"
    settings = (
        json.loads(settings_path.read_text())
        if settings_path.exists()
        else default_settings()
    )
    settings["profile"].update({
        "game": action,
        "power": target_power,
        "dnd": True if action == "on" else previous_dnd,
    })
    validate_settings(settings)
    atomic_json(settings_path, settings)
    return profile


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="colutti-desktopctl")
    commands = root.add_subparsers(dest="command", required=True)
    theme = commands.add_parser("theme")
    themes = theme.add_subparsers(dest="action", required=True)
    for action in ("list", "rollback"):
        item = themes.add_parser(action)
        item.add_argument("--json", action="store_true")
    for action in ("preview", "apply"):
        item = themes.add_parser(action)
        item.add_argument("slug")
        item.add_argument("--json", action="store_true")
    monitors = commands.add_parser("monitors")
    monitor_actions = monitors.add_subparsers(dest="action", required=True)
    apply_cmd = monitor_actions.add_parser("apply")
    apply_cmd.add_argument("--timeout", type=int, default=20)
    confirm = monitor_actions.add_parser("confirm")
    confirm.add_argument("token")
    monitor_actions.add_parser("rollback")
    hdr = monitor_actions.add_parser("hdr")
    hdr.add_argument("state", choices=["on", "off", "status"])
    profile = commands.add_parser("profile")
    profile.add_argument("kind", choices=["game"])
    profile.add_argument("action", choices=["on", "off", "status"])
    commands.add_parser("validate")
    check = commands.add_parser("doctor")
    check.add_argument("--json", action="store_true")
    session = commands.add_parser("session")
    session.add_argument("action", choices=["restore", "status"])
    settings = commands.add_parser("settings")
    settings_actions = settings.add_subparsers(dest="action", required=True)
    settings_actions.add_parser("show")
    settings_apply = settings_actions.add_parser("apply")
    settings_apply.add_argument("path", type=Path)
    settings_hdr = settings_actions.add_parser("set-hdr")
    settings_hdr.add_argument("output")
    settings_hdr.add_argument("state", choices=["on", "off"])
    timeout = commands.add_parser("_monitor-timeout")
    timeout.add_argument("token")
    timeout.add_argument("seconds", type=int)
    theme_timeout = commands.add_parser("_theme-timeout")
    theme_timeout.add_argument("token")
    theme_timeout.add_argument("seconds", type=int)
    return root


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        if args.command == "theme":
            if args.action == "list":
                result = theme_manifests()
            elif args.action == "rollback":
                result = ThemeManager().rollback()
            else:
                result = ThemeManager().apply(args.slug, preview=args.action == "preview")
            print(json.dumps(result, indent=2) if args.json else (
                "\n".join(item["slug"] for item in result) if isinstance(result, list)
                else result["slug"]
            ))
        elif args.command == "monitors":
            manager = MonitorManager()
            if args.action == "apply":
                print(manager.apply(args.timeout))
            elif args.action == "confirm":
                manager.confirm(args.token)
            elif args.action == "hdr":
                print(json.dumps(manager.hdr(args.state), indent=2))
            else:
                manager.rollback()
        elif args.command == "_monitor-timeout":
            time.sleep(args.seconds)
            pending = STATE / "pending-monitor.json"
            if pending.exists() and json.loads(pending.read_text())["token"] == args.token:
                MonitorManager().rollback()
        elif args.command == "_theme-timeout":
            time.sleep(args.seconds)
            ThemeManager().expire_preview(args.token)
        elif args.command == "doctor":
            report, code = doctor()
            print(json.dumps(report, indent=2))
            return code
        elif args.command == "validate":
            return subprocess.run([str(ROOT / "install.sh"), "validate"]).returncode
        elif args.command == "profile":
            print(set_game_profile(args.action)["state"])
        elif args.command == "session":
            script = ROOT / "scripts/session-restore"
            if args.action == "restore":
                return subprocess.run([str(script)]).returncode
            print("ready" if os.environ.get("HYPRLAND_INSTANCE_SIGNATURE") else "offline")
        elif args.command == "settings":
            if args.action == "show":
                result = read_settings()
            elif args.action == "apply":
                result = replace_settings(args.path)
            else:
                result = set_monitor_hdr(args.output, args.state == "on")
            print(json.dumps(result, indent=2))
        return 0
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
