[preferred]
default=hyprland;kde;
org.freedesktop.impl.portal.FileChooser=kde;
org.freedesktop.impl.portal.Settings=kde;
org.freedesktop.impl.portal.ScreenCast=hyprland;
org.freedesktop.impl.portal.Screenshot=hyprland;
