-- Colutti workstation entrypoint for Hyprland 0.56+.
-- Generated runtime values live outside this declarative module tree.
require("modules.monitors")
require("modules.environment")
require("modules.input")
require("modules.workspaces")
require("modules.rules")
require("modules.binds")
require("modules.appearance")
require("modules.permissions")
require("modules.autostart")
require("dms.colors")
require("dms.layout")
require("dms.cursor")
require("dms.windowrules")
