general {
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = /usr/bin/env hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 480
    on-timeout = hyprctl hyprsunset gamma 35
    on-resume = hyprctl hyprsunset gamma 100
}

listener {
    timeout = 720
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = /usr/bin/env hyprctl dispatch dpms off
    on-resume = /usr/bin/env hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
